//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class chemdbEntities : DbContext
{
    public chemdbEntities()
        : base("name=chemdbEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Category> Categories { get; set; }
    public DbSet<CategoryName> CategoryNames { get; set; }
    public DbSet<Language> Languages { get; set; }
    public DbSet<ReactionComment> ReactionComments { get; set; }
    public DbSet<Reaction> Reactions { get; set; }
    public DbSet<ReactionTypeName> ReactionTypeNames { get; set; }
    public DbSet<ReactionType> ReactionTypes { get; set; }
    public DbSet<ReactionCategory> ReactionCategories { get; set; }
}
