//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Category
{
    public Category()
    {
        this.CategoryNames = new HashSet<CategoryName>();
        this.ReactionCategories = new HashSet<ReactionCategory>();
    }

    public int Id { get; set; }
    public int reactionTypeId { get; set; }
    public string defaultName { get; set; }
    public string regex { get; set; }

    public virtual ICollection<CategoryName> CategoryNames { get; set; }
    public virtual ReactionType ReactionType { get; set; }
    public virtual ICollection<ReactionCategory> ReactionCategories { get; set; }
}

public partial class CategoryName
{
    public int Id { get; set; }
    public int categoryId { get; set; }
    public int languageId { get; set; }
    public string name { get; set; }

    public virtual Category Category { get; set; }
    public virtual Language Language { get; set; }
}

public partial class Language
{
    public Language()
    {
        this.CategoryNames = new HashSet<CategoryName>();
        this.ReactionComments = new HashSet<ReactionComment>();
        this.ReactionTypeNames = new HashSet<ReactionTypeName>();
    }

    public int Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<CategoryName> CategoryNames { get; set; }
    public virtual ICollection<ReactionComment> ReactionComments { get; set; }
    public virtual ICollection<ReactionTypeName> ReactionTypeNames { get; set; }
}

public partial class Reaction
{
    public Reaction()
    {
        this.ReactionComments = new HashSet<ReactionComment>();
        this.ReactionCategories = new HashSet<ReactionCategory>();
    }

    public int Id { get; set; }
    public string reagents { get; set; }
    public string products { get; set; }
    public string fakeProducts { get; set; }
    public string conditions { get; set; }
    public int reactionTypeId { get; set; }

    public virtual ICollection<ReactionComment> ReactionComments { get; set; }
    public virtual ReactionType ReactionType { get; set; }
    public virtual ICollection<ReactionCategory> ReactionCategories { get; set; }
}

public partial class ReactionCategory
{
    public int id { get; set; }
    public int categoryId { get; set; }
    public int reactionId { get; set; }

    public virtual Category Category { get; set; }
    public virtual Reaction Reaction { get; set; }
}

public partial class ReactionComment
{
    public int Id { get; set; }
    public int reactionId { get; set; }
    public int languageId { get; set; }
    public string conditions { get; set; }
    public string description { get; set; }

    public virtual Language Language { get; set; }
    public virtual Reaction Reaction { get; set; }
}

public partial class ReactionType
{
    public ReactionType()
    {
        this.Categories = new HashSet<Category>();
        this.Reactions = new HashSet<Reaction>();
        this.ReactionTypeNames = new HashSet<ReactionTypeName>();
    }

    public int Id { get; set; }
    public string defaultName { get; set; }

    public virtual ICollection<Category> Categories { get; set; }
    public virtual ICollection<Reaction> Reactions { get; set; }
    public virtual ICollection<ReactionTypeName> ReactionTypeNames { get; set; }
}

public partial class ReactionTypeName
{
    public int Id { get; set; }
    public int reactionTypeId { get; set; }
    public int languageId { get; set; }
    public string name { get; set; }

    public virtual Language Language { get; set; }
    public virtual ReactionType ReactionType { get; set; }
}
